"""global schema with trot and gallop support

Revision ID: 375e74056e1d
Revises:
Create Date: 2026-05-17 19:42:42.129371

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "375e74056e1d"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "countries",
        sa.Column("code", sa.String(length=2), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("currency_code", sa.String(length=3), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("code"),
    )
    op.create_table(
        "disciplines",
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("sport", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("code"),
    )
    op.create_table(
        "horse_form_snapshots",
        sa.Column("start_id", sa.Uuid(), nullable=False),
        sa.Column("horse_id", sa.Uuid(), nullable=False),
        sa.Column("as_of_date", sa.Date(), nullable=False),
        sa.Column("starts_last_5", sa.Integer(), nullable=True),
        sa.Column("wins_last_5", sa.Integer(), nullable=True),
        sa.Column("places_last_5", sa.Integer(), nullable=True),
        sa.Column("avg_finish_last_5", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("avg_km_time_last_5", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("starts_last_10", sa.Integer(), nullable=True),
        sa.Column("wins_last_10", sa.Integer(), nullable=True),
        sa.Column("places_last_10", sa.Integer(), nullable=True),
        sa.Column("career_starts", sa.Integer(), nullable=True),
        sa.Column("career_wins", sa.Integer(), nullable=True),
        sa.Column("career_places", sa.Integer(), nullable=True),
        sa.Column("career_win_pct", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("days_since_last_start", sa.Integer(), nullable=True),
        sa.Column("best_km_time_s", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="features",
    )
    op.create_index(
        op.f("ix_features_horse_form_snapshots_horse_id"),
        "horse_form_snapshots",
        ["horse_id"],
        unique=False,
        schema="features",
    )
    op.create_index(
        op.f("ix_features_horse_form_snapshots_start_id"),
        "horse_form_snapshots",
        ["start_id"],
        unique=False,
        schema="features",
    )
    op.create_table(
        "person_rolling_stats",
        sa.Column("person_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("as_of_date", sa.Date(), nullable=False),
        sa.Column("window_days", sa.Integer(), nullable=False),
        sa.Column("total_starts", sa.Integer(), nullable=True),
        sa.Column("wins", sa.Integer(), nullable=True),
        sa.Column("places", sa.Integer(), nullable=True),
        sa.Column("win_pct", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("place_pct", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("roi_to_decimal", sa.Numeric(precision=7, scale=4), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="features",
    )
    op.create_index(
        "ix_person_stats_lookup",
        "person_rolling_stats",
        ["person_id", "role", "as_of_date", "window_days"],
        unique=True,
        schema="features",
    )
    op.create_table(
        "track_post_position_stats",
        sa.Column("track_id", sa.Uuid(), nullable=False),
        sa.Column("distance_m", sa.Integer(), nullable=False),
        sa.Column("start_method", sa.String(length=30), nullable=False),
        sa.Column("post_position", sa.Integer(), nullable=False),
        sa.Column("as_of_date", sa.Date(), nullable=False),
        sa.Column("window_days", sa.Integer(), nullable=False),
        sa.Column("total_starts", sa.Integer(), nullable=True),
        sa.Column("wins", sa.Integer(), nullable=True),
        sa.Column("places", sa.Integer(), nullable=True),
        sa.Column("win_pct", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="features",
    )
    op.create_index(
        "ix_pp_stats_lookup",
        "track_post_position_stats",
        ["track_id", "distance_m", "start_method", "post_position", "as_of_date"],
        unique=True,
        schema="features",
    )
    op.create_table(
        "horses",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("sex", sa.String(length=20), nullable=True),
        sa.Column("color", sa.String(length=30), nullable=True),
        sa.Column("birth_year", sa.Integer(), nullable=True),
        sa.Column("country_of_birth", sa.String(length=5), nullable=True),
        sa.Column("father_id", sa.UUID(), nullable=True),
        sa.Column("mother_id", sa.UUID(), nullable=True),
        sa.Column("last_known_owner", sa.String(length=200), nullable=True),
        sa.Column("last_known_breeder", sa.String(length=200), nullable=True),
        sa.Column("career_earnings_minor", sa.BigInteger(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["father_id"],
            ["horses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["mother_id"],
            ["horses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_horses_birth_year"), "horses", ["birth_year"], unique=False)
    op.create_index(op.f("ix_horses_father_id"), "horses", ["father_id"], unique=False)
    op.create_index(op.f("ix_horses_mother_id"), "horses", ["mother_id"], unique=False)
    op.create_index(op.f("ix_horses_name"), "horses", ["name"], unique=False)
    op.create_table(
        "bet_types",
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("operator", sa.String(length=50), nullable=False),
        sa.Column("country_code", sa.String(length=2), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("legs", sa.Integer(), nullable=False),
        sa.Column("is_jackpot", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["country_code"],
            ["countries.code"],
        ),
        sa.PrimaryKeyConstraint("code", "operator"),
        sa.UniqueConstraint("operator", "code", name="uq_bet_type_operator_code"),
    )
    op.create_table(
        "data_sources",
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("country_code", sa.String(length=2), nullable=True),
        sa.Column("base_url", sa.String(length=200), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["country_code"],
            ["countries.code"],
        ),
        sa.PrimaryKeyConstraint("code"),
    )
    op.create_table(
        "persons",
        sa.Column("full_name", sa.String(length=200), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=True),
        sa.Column("last_name", sa.String(length=100), nullable=True),
        sa.Column("short_name", sa.String(length=30), nullable=True),
        sa.Column("birth_year", sa.Integer(), nullable=True),
        sa.Column("country_code", sa.String(length=2), nullable=True),
        sa.Column("location", sa.String(length=200), nullable=True),
        sa.Column("license_type", sa.String(length=100), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["country_code"],
            ["countries.code"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_persons_full_name"), "persons", ["full_name"], unique=False)
    op.create_table(
        "tracks",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("country_code", sa.String(length=2), nullable=False),
        sa.Column("timezone", sa.String(length=50), nullable=True),
        sa.Column("latitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("longitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("surface_types", postgresql.ARRAY(sa.String(length=20)), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["country_code"],
            ["countries.code"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tracks_name"), "tracks", ["name"], unique=False)
    op.create_table(
        "external_ids",
        sa.Column("source_code", sa.String(length=20), nullable=False),
        sa.Column("entity_type", sa.String(length=20), nullable=False),
        sa.Column("external_id", sa.String(length=100), nullable=False),
        sa.Column("internal_id", sa.UUID(), nullable=False),
        sa.Column("first_seen_at", sa.Date(), nullable=False),
        sa.Column("last_seen_at", sa.Date(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["source_code"],
            ["data_sources.code"],
        ),
        sa.PrimaryKeyConstraint("source_code", "entity_type", "external_id"),
        sa.UniqueConstraint(
            "source_code", "entity_type", "external_id", name="uq_external_id_source_type_id"
        ),
    )
    op.create_index(
        "ix_external_id_lookup",
        "external_ids",
        ["source_code", "entity_type", "external_id"],
        unique=False,
    )
    op.create_index(
        "ix_external_id_reverse", "external_ids", ["internal_id", "entity_type"], unique=False
    )
    op.create_index(
        op.f("ix_external_ids_internal_id"), "external_ids", ["internal_id"], unique=False
    )
    op.create_table(
        "meetings",
        sa.Column("track_id", sa.UUID(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("session", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=True),
        sa.Column("currency_code", sa.String(length=3), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["track_id"],
            ["tracks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("track_id", "date", "session", name="uq_meeting_track_date_session"),
    )
    op.create_index("ix_meeting_date", "meetings", ["date"], unique=False)
    op.create_table(
        "raw_payloads",
        sa.Column("source_code", sa.String(length=20), nullable=False),
        sa.Column("entity_type", sa.String(length=20), nullable=False),
        sa.Column("external_id", sa.String(length=200), nullable=False),
        sa.Column("endpoint", sa.String(length=500), nullable=True),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["source_code"],
            ["data_sources.code"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_raw_fetched_at", "raw_payloads", ["fetched_at"], unique=False)
    op.create_index(
        "ix_raw_source_type_external",
        "raw_payloads",
        ["source_code", "entity_type", "external_id"],
        unique=False,
    )
    op.create_table(
        "races",
        sa.Column("meeting_id", sa.UUID(), nullable=False),
        sa.Column("discipline_code", sa.String(length=20), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=500), nullable=True),
        sa.Column("distance_m", sa.Integer(), nullable=True),
        sa.Column("start_method", sa.String(length=30), nullable=True),
        sa.Column("scheduled_start_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("actual_start_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=True),
        sa.Column("surface", sa.String(length=20), nullable=True),
        sa.Column("going", sa.String(length=30), nullable=True),
        sa.Column("track_condition", sa.String(length=30), nullable=True),
        sa.Column("race_class", sa.String(length=50), nullable=True),
        sa.Column("age_restriction", sa.String(length=50), nullable=True),
        sa.Column("sex_restriction", sa.String(length=20), nullable=True),
        sa.Column("total_prize_minor", sa.BigInteger(), nullable=True),
        sa.Column("prize_text", sa.Text(), nullable=True),
        sa.Column("victory_margin", sa.String(length=50), nullable=True),
        sa.Column("scratchings", postgresql.ARRAY(sa.Integer()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["discipline_code"],
            ["disciplines.code"],
        ),
        sa.ForeignKeyConstraint(
            ["meeting_id"],
            ["meetings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("meeting_id", "number", name="uq_race_meeting_number"),
    )
    op.create_index("ix_race_discipline_date", "races", ["discipline_code"], unique=False)
    op.create_index("ix_race_meeting", "races", ["meeting_id"], unique=False)
    op.create_table(
        "weather_observations",
        sa.Column("meeting_id", sa.UUID(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("temperature_c", sa.Numeric(precision=4, scale=1), nullable=True),
        sa.Column("wind_speed_ms", sa.Numeric(precision=4, scale=1), nullable=True),
        sa.Column("wind_direction_deg", sa.Integer(), nullable=True),
        sa.Column("precipitation_mm", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("humidity_pct", sa.Integer(), nullable=True),
        sa.Column("conditions", sa.String(length=50), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["meeting_id"],
            ["meetings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_weather_meeting", "weather_observations", ["meeting_id"], unique=False)
    op.create_table(
        "starts",
        sa.Column("race_id", sa.UUID(), nullable=False),
        sa.Column("horse_id", sa.UUID(), nullable=False),
        sa.Column("rider_id", sa.UUID(), nullable=True),
        sa.Column("trainer_id", sa.UUID(), nullable=True),
        sa.Column("owner_id", sa.UUID(), nullable=True),
        sa.Column("start_number", sa.Integer(), nullable=False),
        sa.Column("post_position", sa.Integer(), nullable=True),
        sa.Column("distance_m", sa.Integer(), nullable=True),
        sa.Column("horse_age_at_start", sa.Integer(), nullable=True),
        sa.Column("horse_earnings_at_start_minor", sa.BigInteger(), nullable=True),
        sa.Column("is_scratched", sa.Boolean(), nullable=False),
        sa.Column("finish_position", sa.Integer(), nullable=True),
        sa.Column("finish_order", sa.Integer(), nullable=True),
        sa.Column("finish_time_s", sa.Numeric(precision=8, scale=3), nullable=True),
        sa.Column("km_time_s", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("lengths_behind_winner", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("prize_money_minor", sa.BigInteger(), nullable=True),
        sa.Column("final_win_odds", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("sulky_type", sa.String(length=30), nullable=True),
        sa.Column("sulky_changed", sa.Boolean(), nullable=True),
        sa.Column("shoes_front", sa.Boolean(), nullable=True),
        sa.Column("shoes_back", sa.Boolean(), nullable=True),
        sa.Column("shoes_front_changed", sa.Boolean(), nullable=True),
        sa.Column("shoes_back_changed", sa.Boolean(), nullable=True),
        sa.Column("jockey_weight_kg", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("blinkers_on", sa.Boolean(), nullable=True),
        sa.Column("tongue_tie_on", sa.Boolean(), nullable=True),
        sa.Column("saddle_cloth_number", sa.Integer(), nullable=True),
        sa.Column("gear_codes", postgresql.ARRAY(sa.String(length=10)), nullable=True),
        sa.Column("incident_notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["horse_id"],
            ["horses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["persons.id"],
        ),
        sa.ForeignKeyConstraint(
            ["race_id"],
            ["races.id"],
        ),
        sa.ForeignKeyConstraint(
            ["rider_id"],
            ["persons.id"],
        ),
        sa.ForeignKeyConstraint(
            ["trainer_id"],
            ["persons.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("race_id", "horse_id", name="uq_start_race_horse"),
    )
    op.create_index("ix_start_horse", "starts", ["horse_id"], unique=False)
    op.create_index("ix_start_race", "starts", ["race_id"], unique=False)
    op.create_index("ix_start_rider", "starts", ["rider_id"], unique=False)
    op.create_index("ix_start_trainer", "starts", ["trainer_id"], unique=False)
    op.create_table(
        "equipment_changes",
        sa.Column("start_id", sa.UUID(), nullable=False),
        sa.Column("item", sa.String(length=50), nullable=False),
        sa.Column("change_type", sa.String(length=20), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["start_id"],
            ["starts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_equipment_start", "equipment_changes", ["start_id"], unique=False)
    op.create_table(
        "odds_snapshots",
        sa.Column("start_id", sa.UUID(), nullable=False),
        sa.Column("bet_type_code", sa.String(length=20), nullable=False),
        sa.Column("bet_type_operator", sa.String(length=50), nullable=False),
        sa.Column("odds_decimal", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("odds_decimal_max", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("pool_share", sa.Numeric(precision=6, scale=5), nullable=True),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_final", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["start_id"],
            ["starts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_odds_start_type_time",
        "odds_snapshots",
        ["start_id", "bet_type_code", "captured_at"],
        unique=False,
    )
    op.create_table(
        "sectional_times",
        sa.Column("start_id", sa.UUID(), nullable=False),
        sa.Column("checkpoint_m", sa.Integer(), nullable=False),
        sa.Column("time_from_start_s", sa.Numeric(precision=7, scale=3), nullable=True),
        sa.Column("position", sa.Integer(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["start_id"],
            ["starts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("start_id", "checkpoint_m", name="uq_sectional_start_checkpoint"),
    )
    op.create_index("ix_sectional_start", "sectional_times", ["start_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_sectional_start", table_name="sectional_times")
    op.drop_table("sectional_times")
    op.drop_index("ix_odds_start_type_time", table_name="odds_snapshots")
    op.drop_table("odds_snapshots")
    op.drop_index("ix_equipment_start", table_name="equipment_changes")
    op.drop_table("equipment_changes")
    op.drop_index("ix_start_trainer", table_name="starts")
    op.drop_index("ix_start_rider", table_name="starts")
    op.drop_index("ix_start_race", table_name="starts")
    op.drop_index("ix_start_horse", table_name="starts")
    op.drop_table("starts")
    op.drop_index("ix_weather_meeting", table_name="weather_observations")
    op.drop_table("weather_observations")
    op.drop_index("ix_race_meeting", table_name="races")
    op.drop_index("ix_race_discipline_date", table_name="races")
    op.drop_table("races")
    op.drop_index("ix_raw_source_type_external", table_name="raw_payloads")
    op.drop_index("ix_raw_fetched_at", table_name="raw_payloads")
    op.drop_table("raw_payloads")
    op.drop_index("ix_meeting_date", table_name="meetings")
    op.drop_table("meetings")
    op.drop_index(op.f("ix_external_ids_internal_id"), table_name="external_ids")
    op.drop_index("ix_external_id_reverse", table_name="external_ids")
    op.drop_index("ix_external_id_lookup", table_name="external_ids")
    op.drop_table("external_ids")
    op.drop_index(op.f("ix_tracks_name"), table_name="tracks")
    op.drop_table("tracks")
    op.drop_index(op.f("ix_persons_full_name"), table_name="persons")
    op.drop_table("persons")
    op.drop_table("data_sources")
    op.drop_table("bet_types")
    op.drop_index(op.f("ix_horses_name"), table_name="horses")
    op.drop_index(op.f("ix_horses_mother_id"), table_name="horses")
    op.drop_index(op.f("ix_horses_father_id"), table_name="horses")
    op.drop_index(op.f("ix_horses_birth_year"), table_name="horses")
    op.drop_table("horses")
    op.drop_index("ix_pp_stats_lookup", table_name="track_post_position_stats", schema="features")
    op.drop_table("track_post_position_stats", schema="features")
    op.drop_index("ix_person_stats_lookup", table_name="person_rolling_stats", schema="features")
    op.drop_table("person_rolling_stats", schema="features")
    op.drop_index(
        op.f("ix_features_horse_form_snapshots_start_id"),
        table_name="horse_form_snapshots",
        schema="features",
    )
    op.drop_index(
        op.f("ix_features_horse_form_snapshots_horse_id"),
        table_name="horse_form_snapshots",
        schema="features",
    )
    op.drop_table("horse_form_snapshots", schema="features")
    op.drop_table("disciplines")
    op.drop_table("countries")
    # ### end Alembic commands ###
