"""add feature tables

Revision ID: 7535c47565d2
Revises: 853441074c95
Create Date: 2026-05-25 23:36:18.718922

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7535c47565d2"
down_revision: str | None = "853441074c95"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "horse_form_snapshots",
        sa.Column("horse_id", sa.UUID(), nullable=False),
        sa.Column("snapshot_date", sa.Date(), nullable=False),
        sa.Column("starts_30d", sa.Integer(), nullable=True),
        sa.Column("starts_90d", sa.Integer(), nullable=True),
        sa.Column("starts_365d", sa.Integer(), nullable=True),
        sa.Column("wins_30d", sa.Integer(), nullable=True),
        sa.Column("wins_90d", sa.Integer(), nullable=True),
        sa.Column("wins_365d", sa.Integer(), nullable=True),
        sa.Column("placed_30d", sa.Integer(), nullable=True),
        sa.Column("placed_90d", sa.Integer(), nullable=True),
        sa.Column("placed_365d", sa.Integer(), nullable=True),
        sa.Column("best_km_time_90d", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("avg_finish_position_5last", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("earnings_per_start_career_minor", sa.BigInteger(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["horse_id"],
            ["horses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="features",
    )
    op.create_index(
        "ix_horse_form_horse_date",
        "horse_form_snapshots",
        ["horse_id", "snapshot_date"],
        unique=False,
        schema="features",
    )
    op.create_table(
        "person_rolling_stats",
        sa.Column("person_id", sa.UUID(), nullable=False),
        sa.Column("snapshot_date", sa.Date(), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("drives_30d", sa.Integer(), nullable=True),
        sa.Column("wins_30d", sa.Integer(), nullable=True),
        sa.Column("win_rate_30d", sa.Numeric(precision=6, scale=4), nullable=True),
        sa.Column("drives_90d", sa.Integer(), nullable=True),
        sa.Column("wins_90d", sa.Integer(), nullable=True),
        sa.Column("win_rate_90d", sa.Numeric(precision=6, scale=4), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["persons.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="features",
    )
    op.create_index(
        "ix_person_rolling_person_date_role",
        "person_rolling_stats",
        ["person_id", "snapshot_date", "role"],
        unique=False,
        schema="features",
    )
    op.create_table(
        "track_post_position_stats",
        sa.Column("track_id", sa.UUID(), nullable=False),
        sa.Column("distance_m", sa.Integer(), nullable=False),
        sa.Column("post_position", sa.Integer(), nullable=False),
        sa.Column("samples", sa.Integer(), nullable=False),
        sa.Column("win_rate", sa.Numeric(precision=6, scale=4), nullable=False),
        sa.Column("place_rate", sa.Numeric(precision=6, scale=4), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["track_id"],
            ["tracks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="features",
    )
    op.create_index(
        "ix_track_pp_track_distance",
        "track_post_position_stats",
        ["track_id", "distance_m"],
        unique=False,
        schema="features",
    )
    op.create_table(
        "start_features",
        sa.Column("start_id", sa.UUID(), nullable=False),
        sa.Column("race_id", sa.UUID(), nullable=False),
        sa.Column("horse_id", sa.UUID(), nullable=False),
        sa.Column("race_date", sa.Date(), nullable=False),
        sa.Column("finish_position", sa.Integer(), nullable=True),
        sa.Column("relevance_score", sa.Integer(), nullable=True),
        sa.Column("career_starts_prior", sa.Integer(), nullable=True),
        sa.Column("career_wins_prior", sa.Integer(), nullable=True),
        sa.Column("career_top3_prior", sa.Integer(), nullable=True),
        sa.Column("career_earnings_minor_prior", sa.BigInteger(), nullable=True),
        sa.Column("career_win_rate", sa.Numeric(precision=6, scale=4), nullable=True),
        sa.Column("career_top3_rate", sa.Numeric(precision=6, scale=4), nullable=True),
        sa.Column("starts_30d", sa.Integer(), nullable=True),
        sa.Column("starts_90d", sa.Integer(), nullable=True),
        sa.Column("starts_365d", sa.Integer(), nullable=True),
        sa.Column("wins_30d", sa.Integer(), nullable=True),
        sa.Column("wins_90d", sa.Integer(), nullable=True),
        sa.Column("wins_365d", sa.Integer(), nullable=True),
        sa.Column("top3_30d", sa.Integer(), nullable=True),
        sa.Column("top3_90d", sa.Integer(), nullable=True),
        sa.Column("avg_finish_pos_last5", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("best_km_time_career", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("best_km_time_90d", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("avg_km_time_last5", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("days_since_last_start", sa.Integer(), nullable=True),
        sa.Column("starts_at_track_prior", sa.Integer(), nullable=True),
        sa.Column("wins_at_track_prior", sa.Integer(), nullable=True),
        sa.Column("starts_at_distance_prior", sa.Integer(), nullable=True),
        sa.Column("rider_drives_30d", sa.Integer(), nullable=True),
        sa.Column("rider_wins_30d", sa.Integer(), nullable=True),
        sa.Column("rider_drives_90d", sa.Integer(), nullable=True),
        sa.Column("rider_wins_90d", sa.Integer(), nullable=True),
        sa.Column("rider_win_rate_90d", sa.Numeric(precision=6, scale=4), nullable=True),
        sa.Column("trainer_starts_30d", sa.Integer(), nullable=True),
        sa.Column("trainer_wins_30d", sa.Integer(), nullable=True),
        sa.Column("trainer_starts_90d", sa.Integer(), nullable=True),
        sa.Column("trainer_wins_90d", sa.Integer(), nullable=True),
        sa.Column("trainer_win_rate_90d", sa.Numeric(precision=6, scale=4), nullable=True),
        sa.Column("father_offspring_wins", sa.Integer(), nullable=True),
        sa.Column("mother_offspring_wins", sa.Integer(), nullable=True),
        sa.Column("shoes_front", sa.Boolean(), nullable=True),
        sa.Column("shoes_back", sa.Boolean(), nullable=True),
        sa.Column("shoes_either_changed", sa.Boolean(), nullable=True),
        sa.Column("sulky_changed", sa.Boolean(), nullable=True),
        sa.Column("num_starters", sa.Integer(), nullable=True),
        sa.Column("post_position", sa.Integer(), nullable=True),
        sa.Column("post_position_normalized", sa.Numeric(precision=6, scale=4), nullable=True),
        sa.Column("horse_age_at_start", sa.Integer(), nullable=True),
        sa.Column("distance_m", sa.Integer(), nullable=True),
        sa.Column("final_win_odds", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("log_final_win_odds", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.Column("odds_rank_in_race", sa.Integer(), nullable=True),
        sa.Column("is_favorite", sa.Boolean(), nullable=True),
        sa.Column("v75_pool_share", sa.Numeric(precision=6, scale=5), nullable=True),
        sa.Column("month", sa.Integer(), nullable=True),
        sa.Column("day_of_week", sa.Integer(), nullable=True),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["horse_id"],
            ["horses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["race_id"],
            ["races.id"],
        ),
        sa.ForeignKeyConstraint(
            ["start_id"],
            ["starts.id"],
        ),
        sa.PrimaryKeyConstraint("start_id"),
        schema="features",
    )
    op.create_index(
        "ix_start_features_horse", "start_features", ["horse_id"], unique=False, schema="features"
    )
    op.create_index(
        "ix_start_features_race", "start_features", ["race_id"], unique=False, schema="features"
    )
    op.create_index(
        "ix_start_features_race_date",
        "start_features",
        ["race_date"],
        unique=False,
        schema="features",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_start_features_race_date", table_name="start_features", schema="features")
    op.drop_index("ix_start_features_race", table_name="start_features", schema="features")
    op.drop_index("ix_start_features_horse", table_name="start_features", schema="features")
    op.drop_table("start_features", schema="features")
    op.drop_index(
        "ix_track_pp_track_distance", table_name="track_post_position_stats", schema="features"
    )
    op.drop_table("track_post_position_stats", schema="features")
    op.drop_index(
        "ix_person_rolling_person_date_role", table_name="person_rolling_stats", schema="features"
    )
    op.drop_table("person_rolling_stats", schema="features")
    op.drop_index("ix_horse_form_horse_date", table_name="horse_form_snapshots", schema="features")
    op.drop_table("horse_form_snapshots", schema="features")
    # ### end Alembic commands ###
